// <auto-generated />
using System;
using AIStockRadar.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AIStockRadar.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250820124643_AddTradingSchema")]
    partial class AddTradingSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AIStockRadar.Models.Security", b =>
                {
                    b.Property<int>("SecurityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("SecurityId");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("Securities");
                });

            modelBuilder.Entity("AIStockRadar.Models.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TradeId");

                    b.HasIndex("SecurityId");

                    b.HasIndex("UserId", "SecurityId", "TradeDate");

                    b.ToTable("Trades", t =>
                        {
                            t.HasCheckConstraint("CK_Trade_Price_NonNegative", "Price >= 0");

                            t.HasCheckConstraint("CK_Trade_Quantity_Positive", "Quantity > 0");
                        });
                });

            modelBuilder.Entity("AIStockRadar.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AIStockRadar.Models.UserHolding", b =>
                {
                    b.Property<int>("HoldingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("AvgCost")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("TEXT");

                    b.Property<int>("SecurityId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("HoldingId");

                    b.HasIndex("SecurityId");

                    b.HasIndex("UserId", "SecurityId")
                        .IsUnique();

                    b.ToTable("UserHoldings", t =>
                        {
                            t.HasCheckConstraint("CK_UserHolding_Quantity_NonNegative", "Quantity >= 0");
                        });
                });

            modelBuilder.Entity("AIStockRadar.Models.UsersInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Capital")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Priority1")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Priority3")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RiskTolerance")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UsersInfos");
                });

            modelBuilder.Entity("AIStockRadar.Models.Trade", b =>
                {
                    b.HasOne("AIStockRadar.Models.Security", "Security")
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIStockRadar.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Security");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStockRadar.Models.UserHolding", b =>
                {
                    b.HasOne("AIStockRadar.Models.Security", "Security")
                        .WithMany()
                        .HasForeignKey("SecurityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AIStockRadar.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Security");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AIStockRadar.Models.UsersInfo", b =>
                {
                    b.HasOne("AIStockRadar.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
